stages:
  - install
  - test
  
install:
    stage: install
    script:
      - pip install --user -r requirements.txt
    tags:
    - shell
    
test:
  stage: test
  script:
    - check/runUnitTests.sh